import Wish from '../models/wish';

export const wishes: Wish[] = [
  {
    id: 1,
    name: 'Bike',
    userId: 'DTroczyk',
    price: 269999,
    description: 'I want a bike for the city and the forest',
    imageUrl:
      'https://www.greenbike.pl/images/level_2_0_black_blue_white_egloss.png.jpg',
    assignedTo: [],
    status: 0,
    quantity: 1,
    visibility: ['joedoe', 'janedoe'],
    isComplete: false,
    isMaxOne: false,
  },
  {
    id: 2,
    name: 'Motorbike 125cm',
    userId: 'DTroczyk',
    price: 599999,
    description: 'Motorbike is good for cities.',
    imageUrl:
      'https://www.autocentrum.pl/ac-file/article/5892c61c582c7da1b2909bb7/honda-cbr-125-r-scigacz-w-miniaturze-07.jpg',
    assignedTo: [],
    status: 0,
    quantity: 1,
    visibility: [],
    isComplete: false,
    isMaxOne: false,
  },
  {
    id: 3,
    name: 'DJI Spark',
    userId: 'DTroczyk',
    price: 150000,
    description: 'DJI Spark is like a flying tank. Good for beginners.',
    imageUrl:
      'https://www.cnet.com/a/img/resize/668d2aca568ea89f72001ef46c323c4f62098ac0/hub/2017/07/14/057fc4a6-5f1b-404b-928f-d91c83e8cf92/dji-spark-0013.jpg?auto=webp&width=768',
    assignedTo: [],
    status: 0,
    quantity: 1,
    visibility: [],
    isComplete: false,
    isMaxOne: false,
  },
  {
    id: 4,
    name: 'Raspberry',
    userId: 'DTroczyk',
    price: 29999,
    description: 'Raspberry for my projects.',
    imageUrl:
      'https://cdn-reichelt.de/bilder/web/xxl_ws/A300/PI4_CASE1_255.png',
    assignedTo: [],
    status: 0,
    quantity: 1,
    isComplete: false,
    isMaxOne: false,
  },
  {
    id: 5,
    name: 'Travel to the America',
    userId: 'joedoe',
    price: 500000,
    description: 'I never been in the USA',
    assignedTo: [],
    status: 0,
    quantity: 1,
    isComplete: false,
    isMaxOne: false,
  },
  {
    id: 6,
    name: 'Factorio',
    userId: 'janedoe',
    price: 7000,
    description: 'I want play Factorio',
    imageUrl:
      'https://cdn.cloudflare.steamstatic.com/steam/apps/427520/capsule_616x353.jpg?t=1620730652',
    assignedTo: [],
    status: 0,
    quantity: 1,
    deadline: new Date(new Date().setDate(new Date().getDate() + 8)),
    isComplete: false,
    isMaxOne: false,
  },
  {
    id: 7,
    name: 'Scooter',
    userId: 'shaanferguson',
    price: 200000,
    description: 'I need this to commute to work.',
    imageUrl:
      'https://hndelectric.pl/wp-content/uploads/2021/03/IMG_8613-600x600.jpg',
    assignedTo: [],
    status: 0,
    quantity: 1,
    isComplete: false,
    isMaxOne: false,
  },
  {
    id: 8,
    name: 'Couch playing',
    userId: 'janedoe',
    description:
      "I'm looking for a player for play in 'Don't Starve Together'.",
    imageUrl: 'https://www.gry-online.pl/Galeria/Html/Artykuly/439661093.jpg',
    assignedTo: [],
    status: 0,
    quantity: 3,
    deadline: new Date(new Date().setDate(new Date().getDate() + 3)),
    isComplete: false,
    isMaxOne: true,
  },
  {
    id: 9,
    name: 'Office chair',
    userId: 'leianeale',
    description: '',
    assignedTo: [
      {
        user: 'joedoe',
        value: 2000,
      },
    ],
    price: 20000,
    status: 2000,
    quantity: 1,
    visibility: true,
    isComplete: false,
    isMaxOne: false,
  },
  {
    id: 10,
    name: 'Orchid',
    userId: 'janedoe',
    description: '',
    imageUrl:
      'https://i.iplsc.com/kwitnacy-storczyk/000ATCZYVJ51QN17-C122-F4.jpg',
    assignedTo: [],
    price: 5000,
    status: 0,
    quantity: 1,
    visibility: true,
    isComplete: false,
    isMaxOne: false,
  },
  {
    imageUrl:
      'https://sklep.rakon.com.pl/raciborz/1425-large_default/goralki-wafelki-rozne-smaki-50g.jpg',
    id: 11,
    name: 'Text check',
    userId: 'janedoe',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. cursus. Proin varius fringilla urna, sit amet aliquet mi pretium ac. Etiam blandit nisi nisl, eget pretium sapien laoreet eu. Duis ac nisi ac leo tincidunt hendrerit tincidunt et ante. Suspendisse tempor cursus orci, at bibendum sapien maximus non. Nunc vestibulum libero risus, id laoreet mauris consequat id. Nam et quam eros. Pellentesque non arcu auctor, tempus elit sit amet, aliquet mi. Suspendisse id ullamcorper massa. Vivamus nec nisi vehicula, interdum magna vitae, hendrerit ipsum. Vivamus nulla velit, faucibus vitae est sed, mollis finibus ex. Aliquam vel enim tellus. Ut vitae massa condimentum urna euismod imperdiet. Integer posuere massa ultrices tincidunt placerat. Praesent nunc est, ullamcorper quis tincidunt a, ultricies a lacus. Duis posuere faucibus dolor, eget dignissim urna placerat a. Vestibulum vel sem vitae dolor scelerisque rhoncus ut eget lacus. Donec sit amet orci quis nisl ultricies sagittis in eget turpis. Curabitur dapibus porttitor ligula, blandit suscipit lectus luctus sed. Donec dignissim mi sed scelerisque hendrerit. Phasellus venenatis ligula id tortor tincidunt mollis. Etiam at nunc ac nulla fermentum luctus a sed nisl. Donec luctus, lectus nec facilisis dapibus, nulla nisi elementum sem, in luctus ligula enim vel elit. Nam a ligula et metus pulvinar laoreet. Ut pulvinar odio at massa viverra, sagittis suscipit ante faucibus. Sed auctor urna ac tellus euismod sollicitudin. Duis condimentum nunc tortor. Nulla in ante imperdiet, facilisis nulla a, imperdiet ipsum. Donec ultricies feugiat est luctus efficitur. Proin mattis cursus leo a ultrices. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed cursus metus. Donec non nunc quis est lobortis sollicitudin et vel ante. Cras ex felis, mattis quis lobortis vitae, condimentum ut risus. Vivamus nisl dolor, ullamcorper nec imperdiet sit amet, bibendum vel nunc. Sed lobortis porta arcu non dignissim. Fusce ut velit interdum, dignissim odio ut, rhoncus diam. Ut facilisis nisl tortor, vel volutpat lacus posuere vitae. Proin commodo lectus dui, ac consectetur orci facilisis id. Quisque arcu odio, viverra ut nibh at, tincidunt sodales sapien. Morbi malesuada mauris eros. Quisque varius felis dui, non posuere tortor porta condimentum. Praesent vel eleifend ligula, hendrerit consequat risus. Suspendisse ultricies tortor eros, eu tristique nisi facilisis vel. Donec malesuada dui at est elementum, sit amet lobortis lectus dictum. Fusce a sagittis risus. Vestibulum accumsan lacus a commodo ultricies. In at odio vestibulum, fringilla eros at, congue lorem. Pellentesque posuere at nibh quis blandit. Aenean scelerisque in nulla cursus gravida. Suspendisse at ex metus. Phasellus suscipit, ligula non convallis molestie, metus urna rutrum sapien, eleifend tincidunt justo urna quis nibh. Etiam ut libero rutrum, mollis metus nec, fermentum diam. Nunc tempor ante sed rutrum eleifend. Cras in enim iaculis est venenatis sagittis semper faucibus justo. Nam sit amet purus leo. Morbi nec ultricies erat, eu pellentesque justo. Sed viverra est vel ultricies accumsan. Duis suscipit lorem nibh, a mattis magna aliquam at. Donec hendrerit quis nisi et sollicitudin. Aliquam bibendum eleifend scelerisque. Mauris sed accumsan nisi. Mauris vitae dolor eu nulla convallis lacinia. Phasellus justo sapien, luctus vel interdum ut, commodo in dolor. Nullam ultricies lacus eget laoreet laoreet. Aenean ac nisi nec ex molestie hendrerit in in tellus. Quisque ut vestibulum magna, vitae pharetra magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam vehicula dapibus tortor, in tincidunt nisl vehicula a. Donec ac suscipit dolor, vel finibus ex. Quisque ullamcorper quam quis aliquet maximus. Fusce volutpat finibus lectus, nec laoreet massa. Nulla vitae molestie odio. Donec in libero ac massa consectetur aliquet. Donec consequat eget ipsum vitae placerat. Phasellus sodales fringilla pellentesque. Ut tristique tincidunt nunc ut blandit. Aenean purus elit, scelerisque fermentum ex id, ultricies auctor libero. Fusce nec bibendum mi. Cras eu tincidunt tortor. Ut iaculis arcu nec metus efficitur interdum. Morbi bibendum, nibh a iaculis efficitur, lorem sapien scelerisque mi, nec elementum arcu ex a nisi. Praesent venenatis maximus odio sit amet maximus. Phasellus dignissim, metus ac eleifend mollis, diam elit varius tortor, ut pellentesque urna enim vitae eros. Aliquam blandit eu arcu venenatis semper. Quisque pulvinar vestibulum massa ut elementum. Donec lacinia, arcu at cursus aliquet, turpis odio consequat felis, euismod vestibulum neque odio ut justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam sit amet orci dignissim sem rutrum pretium at vel neque. Cras eget elementum erat, rutrum auctor mauris. Sed vestibulum ligula dui, sit amet elementum purus venenatis sed. Curabitur ac libero risus. Quisque convallis massa eu erat blandit fermentum. Sed erat ante, congue vitae mauris eget, vulputate elementum mi. Suspendisse potenti. Integer imperdiet quis metus sed pharetra. Aenean id odio luctus, semper dui non, condimentum magna. Mauris scelerisque sed mi vitae mattis. Aliquam posuere ligula et enim placerat mattis. Proin tempor, justo eget mattis vehicula, dolor nibh tempus purus, vel efficitur purus magna ut ex. Fusce dictum scelerisque mi, vel efficitur est accumsan eu. Nunc porttitor mi id tortor tempus tincidunt. Mauris nibh eros, tincidunt et mi id, placerat commodo ante. Fusce molestie orci magna, pretium mattis odio posuere et. Suspendisse sed velit aliquet, accumsan tellus sit amet, accumsan est. Nunc maximus, nibh quis volutpat aliquet, lorem nisi lobortis lorem, et rutrum diam dui eu augue. Quisque ipsum leo, eleifend non dapibus vitae, accumsan eget ipsum. Quisque ultricies, ante et luctus maximus, orci sem tristique neque, vel egestas erat ligula ac magna. Proin ornare condimentum sodales. Proin tincidunt ultrices massa et efficitur. Curabitur commodo, nulla sit amet hendrerit posuere, nisi dui molestie erat, quis placerat mi arcu id risus. In diam neque, elementum sed faucibus sed, ultrices vitae quam. Donec varius tristique mauris, vitae condimentum eros vulputate a. Suspendisse efficitur lectus nec justo sagittis hendrerit. Integer facilisis maximus erat nec dapibus. Nullam et tortor sed diam pellentesque congue ut sed libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus euismod ac tortor eget posuere. Nunc scelerisque malesuada tellus at cursus. Pellentesque mollis est sed laoreet lacinia. Proin scelerisque lacinia erat, nec aliquam elit lacinia sed.',
    assignedTo: [],
    price: 5000,
    status: 0,
    quantity: 5,
    visibility: true,
    isComplete: false,
    isMaxOne: true,
  },
];
