name: Node.js CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.10"
      - name: Install dependencies
        run: npm i
      - run: npm run build

  test:
    runs-on: windows-latest

    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v0.0.0
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.10"
      - name: Install dependencies
        run: npm i
      - run: npm run test-headless
